Ansible role that setsup a mariadb server instance
stuvusIT/mariadb pull request #1
Opened 2017-04-14 20:54 UTC by Scriptkiddi

Added defaults that are equal to the default values from my-huge.cnf
besides one value that "skip-networking" is by default true so that
every network connection will be rejected when the server is run with
default values

2017-04-14 23:03 UTC, SlothOfAnarchy requested changes

2017-04-14 23:03 UTC, SlothOfAnarchy commented on README.md
> +# Role Name
set role name

2017-04-14 23:03 UTC, SlothOfAnarchy commented on meta/main.yml
> +  description: Ansible role to configure and start an mariadb server
"a" instead of "an"

2017-04-14 23:03 UTC, SlothOfAnarchy commented on templates/my.cnf.j2
> +#password   = your_password
add password var, maybe even mark it mandatory

2017-04-14 23:03 UTC, SlothOfAnarchy commented on templates/my.cnf.j2
> +#tmpdir     = /tmp/
add tempdir var

2017-04-14 23:03 UTC, SlothOfAnarchy commented on templates/my.cnf.j2
> +# Example MariaDB config file for very large systems.
mark as ansible_managed

2017-04-14 23:03 UTC, SlothOfAnarchy commented on templates/my.cnf.j2
> +#innodb_log_group_home_dir = @localstatedir@
add innodb support

2017-04-14 23:03 UTC, SlothOfAnarchy commented on tasks/main.yml
> +# tasks file for .
remove or correct comment

2017-04-14 23:03 UTC, SlothOfAnarchy commented on README.md
> +Read the mariadb doc to get to know what vars can be set
link?

2017-04-14 23:03 UTC, SlothOfAnarchy commented on templates/my.cnf.j2
> +# to the master - required
you **could** add vars for replication

2017-04-17 14:28 UTC, Scriptkiddi commented on README.md
> +# Role Name
done

2017-04-17 14:35 UTC, SlothOfAnarchy approved these changes

2017-04-17 14:36 UTC, merged

2017-04-30 17:48 UTC, dasJ commented on templates/my.cnf.j2
> +# Replication Slave (comment out master section to use this)
@Scriptkiddi Why the fuck is there a huge commented out area?